---
name: Overseerr
version: dev
slug: overseerr
description: Request management and media discovery tool for the Plex ecosystem
url: https://github.com/hassio-addons/addon-overseerr/tree/main/README.md
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 1337
ingress_stream: true
webui: http://[HOST]:[PORT:5055]
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  5055/tcp: 5055
